# Generated by Django 4.2.1 on 2023-07-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='seat_number',
            field=models.CharField(),
        ),
    ]
